import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const kidsGames = [
  {
    name: 'Emoji Pattern Detective',
    slug: 'emoji-pattern',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Find the next emoji in the pattern! Trains pattern recognition and logical thinking.',
    benefits: ['Pattern Recognition', 'Logical Thinking', 'Attention to Detail'],
    rules: ['Look at the emoji sequence', 'Figure out the repeating pattern', 'Pick the emoji that comes next'],
    gameType: 'kids_pattern',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 101,
  },
  {
    name: 'Color Mixer Lab',
    slug: 'color-mixer',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Mix primary colors to create new ones! Learn how red, blue, and yellow combine.',
    benefits: ['Color Theory', 'Logical Deduction', 'Visual Learning'],
    rules: ['See the target color', 'Pick which two primary colors to mix', 'Red+Blue=Purple, Red+Yellow=Orange, Blue+Yellow=Green'],
    gameType: 'kids_color_mix',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 102,
  },
  {
    name: 'Animal Sort',
    slug: 'animal-sort',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Sort animals into the right groups! Can it fly? Does it swim? You decide!',
    benefits: ['Classification Skills', 'Critical Thinking', 'Biology Knowledge'],
    rules: ['Read the sorting question', 'Place each animal into the correct group', 'Sort all animals then check your answers'],
    gameType: 'kids_animal_sort',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 103,
  },
  {
    name: 'Shape Builder',
    slug: 'shape-builder',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Complete the shape and color patterns! Great for building math foundations.',
    benefits: ['Pattern Recognition', 'Spatial Reasoning', 'Math Foundations'],
    rules: ['Look at the shape sequence', 'Find the repeating pattern', 'Choose what comes next'],
    gameType: 'kids_shape_builder',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 104,
  },
  {
    name: 'Story Sequencer',
    slug: 'story-sequence',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Put the story panels in the right order! Think about what happens first, next, and last.',
    benefits: ['Sequential Thinking', 'Reading Comprehension', 'Cause & Effect'],
    rules: ['See the scrambled story panels', 'Tap them in the correct order (1st to last)', 'Check if your sequence tells the right story'],
    gameType: 'kids_story_sequence',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 105,
  },
  {
    name: 'Odd One Out',
    slug: 'odd-one-out',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Find the item that doesn\'t belong! Sharpen your analytical thinking.',
    benefits: ['Analytical Thinking', 'Categorization', 'Visual Discrimination'],
    rules: ['Look at four items', 'Find the one that doesn\'t belong with the others', 'Think about what the other three have in common'],
    gameType: 'kids_odd_one_out',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 106,
  },
  {
    name: 'Mirror Match',
    slug: 'mirror-match',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Create the mirror image of a pattern! Trains symmetry and spatial thinking.',
    benefits: ['Spatial Reasoning', 'Symmetry Understanding', 'Visual Processing'],
    rules: ['See the original pattern on the left', 'Click cells to create its mirror image on the right', 'Flip left-right like looking in a mirror'],
    gameType: 'kids_mirror_match',
    gridSize: 3,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 107,
  },
  {
    name: 'Number Ninja',
    slug: 'number-ninja',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Quick mental math challenges! Add, subtract, and multiply your way to victory.',
    benefits: ['Mental Math', 'Processing Speed', 'Number Sense'],
    rules: ['Solve the math problem quickly', 'Pick the correct answer from 4 options', 'Faster answers earn more bonus points'],
    gameType: 'kids_number_ninja',
    gridSize: 0,
    timeLimit: 10,
    maxLevel: 30,
    sortOrder: 108,
  },
  {
    name: 'Word Scramble',
    slug: 'word-scramble',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Unscramble the letters to find the hidden word! Builds vocabulary and spelling skills.',
    benefits: ['Vocabulary', 'Spelling', 'Word Recognition'],
    rules: ['See the scrambled letters', 'Figure out the original word', 'Use the hint if you need help (fewer points)'],
    gameType: 'kids_word_scramble',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 109,
  },
  {
    name: 'Maze Runner',
    slug: 'maze-runner',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Navigate through mazes to reach the exit! Trains problem-solving and spatial navigation.',
    benefits: ['Problem Solving', 'Spatial Navigation', 'Planning Ahead'],
    rules: ['Navigate from start to the flag', 'Use arrow keys or tap/click adjacent cells', 'Fewer moves = higher score'],
    gameType: 'kids_maze',
    gridSize: 7,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 110,
  },
  {
    name: 'Treasure Map',
    slug: 'treasure-map',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Memorize the directions and follow them to find hidden treasure! Trains memory and direction sense.',
    benefits: ['Directional Thinking', 'Working Memory', 'Spatial Awareness'],
    rules: ['Memorize the sequence of directions', 'Navigate the grid following those directions', 'Find the treasure with the fewest extra moves'],
    gameType: 'kids_treasure_map',
    gridSize: 5,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 111,
  },
  {
    name: 'Code Breaker',
    slug: 'code-breaker',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Crack secret codes! Each number is a letter (A=1, B=2...). Decode the hidden word.',
    benefits: ['Logical Deduction', 'Problem Solving', 'Alphabet Knowledge'],
    rules: ['Each number represents a letter (A=1, B=2, C=3...)', 'Decode the numbers to find the word', 'Use the alphabet chart if needed'],
    gameType: 'kids_code_breaker',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 112,
  },
  {
    name: 'Balance Scale',
    slug: 'balance-scale',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Which side is heavier? Compare groups of objects and guess the heavier side!',
    benefits: ['Estimation', 'Logical Reasoning', 'Math Concepts'],
    rules: ['Look at objects on both sides of the scale', 'Guess which side is heavier', 'Consider how many of each item there are'],
    gameType: 'kids_balance',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 113,
  },
  {
    name: 'Spot the Difference',
    slug: 'spot-difference',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Find the differences between two emoji grids! Trains attention to detail.',
    benefits: ['Attention to Detail', 'Visual Comparison', 'Focus'],
    rules: ['Compare the two emoji grids side by side', 'Tap the changed emojis in the right picture', 'Find all differences to score points'],
    gameType: 'kids_spot_diff',
    gridSize: 4,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 114,
  },
  {
    name: 'Rhythm Repeat',
    slug: 'rhythm-repeat',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Watch the colors light up and repeat the pattern! Like Simon Says with colors.',
    benefits: ['Sequence Memory', 'Auditory-Visual Processing', 'Concentration'],
    rules: ['Watch which colored pads light up', 'Repeat the sequence in the same order', 'Each round adds one more step to the sequence'],
    gameType: 'kids_rhythm',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 115,
  },
  {
    name: 'Pixel Artist',
    slug: 'pixel-artist',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Memorize the pixel art then recreate it from memory! Train your visual memory.',
    benefits: ['Visual Memory', 'Spatial Recall', 'Attention to Detail'],
    rules: ['Study the pixel art for a few seconds', 'Recreate it by toggling cells on/off', 'Match the original pattern as closely as possible'],
    gameType: 'kids_pixel_art',
    gridSize: 4,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 116,
  },
  {
    name: 'Word Chain',
    slug: 'kids-word-chain',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Build a chain of words! Each word must start with the last letter of the previous word.',
    benefits: ['Verbal Fluency', 'Vocabulary', 'Quick Thinking'],
    rules: ['A starting word is given', 'Type a word that starts with its last letter', 'Keep the chain going before time runs out'],
    gameType: 'kids_word_chain',
    gridSize: 0,
    timeLimit: 60,
    maxLevel: 30,
    sortOrder: 117,
  },
  {
    name: 'Guess the Rule',
    slug: 'guess-rule',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Two groups of items follow a hidden rule. Figure it out and sort new items correctly!',
    benefits: ['Inductive Reasoning', 'Critical Thinking', 'Pattern Analysis'],
    rules: ['Look at two groups of items', 'Figure out the sorting rule', 'Place the new item in the correct group'],
    gameType: 'kids_guess_rule',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 118,
  },
  {
    name: 'Tower Builder',
    slug: 'tower-builder',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Stack numbered blocks in ascending order! Plan ahead to build the tallest tower.',
    benefits: ['Planning & Strategy', 'Number Ordering', 'Decision Making'],
    rules: ['Blocks arrive one at a time with a number', 'Place them on the tower — each must be ≥ the block below', 'Skip blocks that don\'t fit — build as tall as you can'],
    gameType: 'kids_tower',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 119,
  },
  {
    name: 'Emotion Detective',
    slug: 'emotion-detective',
    category: 'kids-zone',
    difficulty: 'beginner',
    description: 'Match the right emotion to each scenario! Build emotional intelligence and empathy.',
    benefits: ['Emotional Intelligence', 'Empathy', 'Social Awareness'],
    rules: ['Read the scenario', 'Pick the emoji that best matches how you\'d feel', 'Learn about different emotions and why we feel them'],
    gameType: 'kids_emotion',
    gridSize: 0,
    timeLimit: 0,
    maxLevel: 30,
    sortOrder: 120,
  },
]

async function main() {
  console.log('🧒 Seeding Kids Zone games...')

  for (const g of kidsGames) {
    await prisma.game.upsert({
      where: { slug: g.slug },
      update: g,
      create: g,
    })
    console.log(`  ✓ ${g.name}`)
  }

  console.log(`\n🎉 Done! ${kidsGames.length} kids games seeded.`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
